# Production-specific settings with Nginx
services:
  app:
    env_file:
      - .env.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=postgres
    container_name: marytv-backend
    restart: always

  postgres:
    env_file:
      - .env.prod
    container_name: marytv-postgres
    restart: always

  nginx:
    build:
      context: ..
      dockerfile: backend/nginx/frontend.Dockerfile
    container_name: marytv-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - app-network
    restart: always

networks:
  app-network: