# Development-specific overrides
services:
  app:
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    image: mary-tv-backend:dev
    container_name: marytv-backend-dev  # Dev-specific variant for local testing

  postgres:
    ports:
      - "5432:5432"
    container_name: marytv-postgres-dev  # Dev-specific variant