spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000  # 1 hour
logging:
  level:
    org.springframework.security: DEBUG