spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:marytv_prod}
    username: ${DB_USER:prod_user}
    password: ${DB_PASS:prod_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 # 1 hour

server:
  port: 8080
  forward-headers-strategy: NATIVE